[package]
name = "json-melt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
genson-rs = "0.2.0"
simd-json = "0.13"
regex = "1.10"
once_cell = "1.19"
